# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # 2.runtime environment
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 5.0
          # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
          #source-url: # optional
          # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
          owner: weibinlong
          # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
          #config-file: # optional
      # 3.build
      - name: Build with dotnet
        run: dotnet build --configuration Release
      # 4.Install Nuget
      - name: Install Nuget
        run: |
           $sourceNugetExe = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
           $targetNugetExe = "nuget.exe"
           Invoke-WebRequest $sourceNugetExe -OutFile $targetNugetExe
     # 5. Push  package
      - name: Push generated package to GitHub registry
        run: |        
          .\nuget push .\aspnet-core\modules\account\LINGYUN.Abp.Account.Application.Contracts\bin\Release*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbols 
